export const FETCH_TASKS_REQUEST = 'FETCH_TASKS_REQUEST';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_SORT = 'FETCH_TASKS_SORT';
export const FETCH_TASKS_FAILURE = 'FETCH_TASKS_FAILURE';
